require('dotenv').config();
const express=require('express'); const multer=require('multer'); const path=require('path'); const fs=require('fs');
const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken'); const cookieParser=require('cookie-parser'); const {Pool}=require('pg');
const app=express(); const port=process.env.PORT||3000;
if(!process.env.DATABASE_URL||!process.env.JWT_SECRET||!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD) console.warn('Configure DATABASE_URL, JWT_SECRET, ADMIN_EMAIL e ADMIN_PASSWORD no .env');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('sslmode=require')?undefined:{rejectUnauthorized:false}});
app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true})); app.use(cookieParser());
const uploadDir=path.join(__dirname,'public','uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase(); cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+ext)}});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(f.mimetype))});
function tokenFor(email){return jwt.sign({email},process.env.JWT_SECRET,{expiresIn:'8h'})}
function auth(req,res,next){try{const t=req.cookies.admin_token;if(!t) return res.status(401).json({error:'Não autenticado'}); req.admin=jwt.verify(t,process.env.JWT_SECRET); next()}catch(e){return res.status(401).json({error:'Sessão expirada'})}}
async function init(){await pool.query(fs.readFileSync(path.join(__dirname,'sql/schema.sql'),'utf8')); await pool.query(fs.readFileSync(path.join(__dirname,'sql/orders.sql'),'utf8')); const h=await bcrypt.hash(process.env.ADMIN_PASSWORD||'change-me',12); if(process.env.ADMIN_EMAIL) await pool.query('INSERT INTO admins(email,password_hash) VALUES($1,$2) ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash',[process.env.ADMIN_EMAIL,h]);}
app.post('/api/login',async(req,res)=>{try{const {email,password}=req.body; const q=await pool.query('SELECT * FROM admins WHERE email=$1',[email]); if(!q.rowCount||!await bcrypt.compare(password,q.rows[0].password_hash)) return res.status(401).json({error:'E-mail ou senha inválidos'}); res.cookie('admin_token',tokenFor(email),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:8*60*60*1000}); res.json({ok:true})}catch(e){res.status(500).json({error:'Erro no login'})}});
app.post('/api/logout',(req,res)=>{res.clearCookie('admin_token');res.json({ok:true})}); app.get('/api/me',auth,(req,res)=>res.json({email:req.admin.email}));
app.get('/api/products',async(req,res)=>{try{const q=await pool.query('SELECT * FROM products WHERE active=true ORDER BY created_at DESC');res.json(q.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/products/:id',async(req,res)=>{try{const q=await pool.query('SELECT * FROM products WHERE id=$1 AND active=true',[req.params.id]); if(!q.rowCount)return res.status(404).json({error:'Produto não encontrado'});res.json(q.rows[0])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/products',auth,async(req,res)=>{const q=await pool.query('SELECT * FROM products ORDER BY id DESC');res.json(q.rows)});
app.post('/api/products',auth,upload.single('image'),async(req,res)=>{try{const b=req.body;const image=req.file?'/uploads/'+req.file.filename:(b.image||'');const q=await pool.query(`INSERT INTO products(name,category,type,factory_cost,sale_price,stock,image,description,specifications,sizes,colors,wholesale_min) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[b.name,b.category||'Outros',b.type||'varejo',Number(b.factory_cost)||0,b.sale_price===''?null:Number(b.sale_price),parseInt(b.stock)||0,image,b.description||'',b.specifications||'',b.sizes||'',b.colors||'',parseInt(b.wholesale_min)||1]);res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/products/:id',auth,upload.single('image'),async(req,res)=>{try{const old=await pool.query('SELECT * FROM products WHERE id=$1',[req.params.id]);if(!old.rowCount)return res.status(404).json({error:'Não encontrado'});const b=req.body;const image=req.file?'/uploads/'+req.file.filename:(b.image??old.rows[0].image);const q=await pool.query(`UPDATE products SET name=$1,category=$2,type=$3,factory_cost=$4,sale_price=$5,stock=$6,image=$7,description=$8,specifications=$9,sizes=$10,colors=$11,wholesale_min=$12,updated_at=NOW() WHERE id=$13 RETURNING *`,[b.name,b.category||'Outros',b.type||'varejo',Number(b.factory_cost)||0,b.sale_price===''?null:Number(b.sale_price),parseInt(b.stock)||0,image,b.description||'',b.specifications||'',b.sizes||'',b.colors||'',parseInt(b.wholesale_min)||1,req.params.id]);res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/products/:id',auth,async(req,res)=>{await pool.query('UPDATE products SET active=false,updated_at=NOW() WHERE id=$1',[req.params.id]);res.json({ok:true})});

app.post('/api/orders',async(req,res)=>{try{const {customer,items,payment_method='whatsapp',notes=''}=req.body;if(!customer?.name||!customer?.phone||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Dados do pedido incompletos'});const ids=items.map(i=>Number(i.product_id)).filter(Boolean);const q=await pool.query('SELECT * FROM products WHERE id=ANY($1::int[]) AND active=true',[ids]);const map=new Map(q.rows.map(p=>[p.id,p]));let total=0,rows=[];for(const it of items){const p=map.get(Number(it.product_id));const qty=Math.max(1,parseInt(it.quantity)||1);if(!p||Number(p.stock)<qty)return res.status(400).json({error:'Produto sem estoque ou quantidade indisponível: '+(p?.name||it.product_id)});const unit=Number(p.sale_price??Number(p.factory_cost)*1.4);const sub=unit*qty;total+=sub;rows.push({p,qty,unit,sub})}const client=await pool.connect();try{await client.query('BEGIN');const o=await client.query('INSERT INTO orders(customer_name,customer_phone,customer_email,address_json,payment_method,total,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[customer.name,customer.phone,customer.email||'',customer.address||{},payment_method,total,notes]);for(const r of rows){await client.query('INSERT INTO order_items(order_id,product_id,product_name,unit_price,quantity,subtotal) VALUES($1,$2,$3,$4,$5,$6)',[o.rows[0].id,r.p.id,r.p.name,r.unit,r.qty,r.sub]);await client.query('UPDATE products SET stock=stock-$1,updated_at=NOW() WHERE id=$2',[r.qty,r.p.id])}await client.query('COMMIT');res.json({order:o.rows[0],total})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/admin/orders',auth,async(req,res)=>{const q=await pool.query('SELECT o.*,COALESCE(json_agg(json_build_object(\'product_id\',i.product_id,\'name\',i.product_name,\'quantity\',i.quantity,\'unit_price\',i.unit_price)) FILTER (WHERE i.id IS NOT NULL),\'[]\') items FROM orders o LEFT JOIN order_items i ON i.order_id=o.id GROUP BY o.id ORDER BY o.created_at DESC');res.json(q.rows)});
app.patch('/api/admin/orders/:id',auth,async(req,res)=>{const allowed=['recebido','confirmado','pago','enviado','concluido','cancelado'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Status inválido'});const q=await pool.query('UPDATE orders SET status=$1 WHERE id=$2 RETURNING *',[req.body.status,req.params.id]);res.json(q.rows[0])});

app.use(express.static(path.join(__dirname,'public'))); app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
init().then(()=>app.listen(port,()=>console.log('ATACAREJO Etapa 1 em http://localhost:'+port))).catch(e=>{console.error(e);process.exit(1)});
